Bump controller image openssh dependency to 8.6_p1-r1
the openssh=8.6_p1-r0 breaks deps
```
Step 2/7 : RUN apk add --no-cache mercurial openssh=8.6_p1-r0
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/main
---> Running in 842ffd0552c3
fetch
http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch
https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch
https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  openssh-8.6_p1-r1:
    breaks: world[openssh=8.6_p1-r0]
The command '/bin/sh -c apk add --no-cache mercurial openssh=8.6_p1-r0 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main' returned a non-zero code: 1
```